chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, ChatView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^d/(?P<username>[\w.@+-]+)/", ThreadView.as_view()),
    path("chat/<slug:slug>/", ChatView.as_view(), name="chat"),
]

post_stalker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from machina import urls as machina_urls

from users.views.userena import profile_detail as pda_detail

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('forum/', include(machina_urls)),
                  path('users/', include('userena.urls')),
                  path('u/funcs/', include('users.urls.functional')),
                  path('pda/', include('users.urls.pda')),
                  path('chats/', include('chat.urls')),

                  path("pda_id/<int:uid>/", pda_detail, name="user_pda_id"),
              ] + static(settings.STATIC_URL, docuent_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import funcs, equip

app_name = "users"
urlpatterns = [
    path("rep/<int:pk>/", funcs.ReputationDetailView.as_view(), name="user_reputation"),
    path("add/rep/<int:user_id>/", funcs.ReputationCreateView.as_view(), name="user_reputation_add"),

    path("money/<int:pk>/", funcs.TransactionDetailView.as_view(), name="user_money"),
    path("transfer/money/<int:user_id>/", funcs.TransactionCreateView.as_view(), name="user_money_transfer"),

    path("awards/<int:pk>/", funcs.AwardDetailView.as_view(), name="user_awards"),
    path("add/award/<int:user_id>/", funcs.AwardAddView.as_view(), name="user_award_add"),

    path("img_select/", funcs.SelectChatImageView.as_view(), name="img_select"),
    path("status_set/", funcs.ChangeStatusView.as_view(), name="set_status"),
    path("change_username/", funcs.ChangeUsername.as_view(), name="change_username"),

    path("shop/", equip.EquipmentShop.as_view(), name="equip_shop"),

]

users/views.py
import re

from django.http import JsonResponse
from django.views import generic
from django.views.generic.list import MultipleObjectMixin

from users import models as u_model
from users.forms import AddRepForm, ChoiceImageColorForm, SetStatus, ChangeUsernameForm
from utils import views as util

U_SETTIGNS = u_model.UserSettings.load()


class ReputationDetailView(generic.DetailView, MultipleObjectMixin):
    model = u_model.User
    template_name = "users/reputation.html"
    context_object_name = "user"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = self.object.to_rep.all()
        context = super().get_context_data(object_list=object_list, **kwargs)
        return context


class ReputationCreateView(generic.CreateView):
    model = u_model.Reputation
    form_class = AddRepForm
    user_id = None
    success_url = "/"

    def get(self, request, *args, **kwargs):
        get = util.view_get(request, int(self.kwargs["user_id"]), "users.add_reputation", "respect_changing")
        if get is True:
            return super().get(self, request, *args, **kwargs)
        return get

    def post(self, request, *args, **kwargs):
        author = request.user
        subj = request.POST.get('subject')
        operation_type = request.POST.get('type')
        try:
            user = u_model.User.objects.get(id=int(self.kwargs["user_id"]))
        except u_model.User.DoesNotExist:
            return JsonResponse({"result": False,
                                 "cause": "Пользователя не существует"})
        if user.id == request.user.id:
            return JsonResponse({"result": False,
                                 "cause": "Вы не можете изменить репутацию самому себе"})
        value = 0
        if operation_type == "minus":
            value = -1
        elif operation_type == "plus":
            value = +1
        user.respect += value
        data = {
            "id": u_model.Reputation.objects.last().id + 1,
            "from_user": author,
            "to_user": user,
            "value": value,
        }
        respect = u_model.Reputation(id=data["id"], from_user=data["from_user"], to_user=data["to_user"], subject=subj,
                                     value=value)
        respect.save()
        user.save()
        return JsonResponse({"result": bool(respect),
                             "current_respect": user.respect})


class TransactionDetailView(generic.DetailView, MultipleObjectMixin):
    model = u_model.User
    template_name = "users/money_balance.html"
    context_object_name = "user"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = self.object.to_transaction.all()
        user_money = self.request.user.money
        context = super().get_context_data(object_list=object_list, user_money=user_money, **kwargs)
        return context


class TransactionCreateView(generic.CreateView):
    model = u_model.MoneyTransaction
    user_id = None
    success_url = "/"
    fields = ["value", "message"]

    def get(self, request, *args, **kwargs):
        get = util.view_get(request, int(self.kwargs["user_id"]), "users.add_moneytransaction", "money_transfer")
        if get is True:
            return super().get(self, request, *args, **kwargs)
        return get

    def post(self, request, *args, **kwargs):
        author = request.user
        msg = request.POST.get('message')
        value = int(request.POST.get('value'))
        if value < 0:
            return JsonResponse({"result": False,
                                 "cause": "Значение должно быть больше ноля"})
        try:
            user = u_model.User.objects.get(id=int(self.kwargs["user_id"]))
        except u_model.User.DoesNotExist:
            return JsonResponse({"result": False,
                                 "cause": "Пользователя не существует"})
        if user.id == request.user.id:
            return JsonResponse({"result": False,
                                 "cause": "Вы не можете перевести деньги самому себе"})

        if author.money < value:
            return JsonResponse({"result": False,
                                 "cause": "На вашем счету недостаточно средств для перевода"})
        author.money -= value
        user.money += value
        data = {
            "from_user": author,
            "to_user": user,
        }
        transaction = u_model.MoneyTransaction(from_user=data["from_user"], to_user=data["to_user"],
                                               message=msg,
                                               value=value)
        transaction.save()
        author.save()
        user.save()
        return JsonResponse({"result": bool(transaction),
                             "user_currency": user.money,
                             "my_currency": author.money,
                             })

    def get_context_data(self, **kwargs):
        user_money = self.request.user.money
        context = super().get_context_data(user_money=user_money, **kwargs)
        return context


class SelectChatImageView(generic.FormView):
    template_name = "users/img_select.html"
    form_class = ChoiceImageColorForm

    def get_context_data(self, **kwargs):
        settings = {"ico_price": U_SETTIGNS.chat_ico_price,
                    "color_price": U_SETTIGNS.chat_color_price}
        context = super().get_context_data(settings=settings, **kwargs)
        return context

    def post(self, request, *args, **kwargs):
        user = request.user
        amount, icon = 0, None
        if request.POST.get('icon'):
            icon = int(request.POST.get('icon'))
        color = request.POST.get('color')
        if not icon and not color:
            return JsonResponse({
                "result": False,
                "cause": "Нет данных для измения"
            })
        if icon and user.money < U_SETTIGNS.chat_ico_price:
            return JsonResponse({
                "result": False,
                "cause": f"Недостаточно {U_SETTIGNS.chat_ico_price - user.money} ДФ для изменения иконки"
            })
        elif not icon or user.ico_num == icon:
            pass
        else:
            user.ico_num = icon
            user.money -= U_SETTIGNS.chat_ico_price
            amount -= U_SETTIGNS.chat_ico_price
        if color and user.money < U_SETTIGNS.chat_color_price:
            return JsonResponse({
                "result": False,
                "cause": f"Недостаточно {U_SETTIGNS.chat_color_price - user.money} ДФ для изменения цвета"
            })
        elif not color or user.chat_color == color:
            pass
        else:
            user.chat_color = color
            user.money -= U_SETTIGNS.chat_color_price
            amount -= U_SETTIGNS.chat_color_price
        user.save()
        transaction = u_model.MoneyTransaction(
            from_user_id=None,
            to_user_id=user.id,
            message="Измение иконки/цвета никнейма в чате",
            value=amount
        )
        transaction.save()
        icon = user.ico_num if not icon else icon
        return JsonResponse({
            "result": True,
            "cause": "Данные успешно изменены",
            "src": f"/static/post_stalker/ico/Chat/{icon}.png",
        })


class ChangeStatusView(generic.FormView):
    form_class = SetStatus
    template_name = "users/change_status.html"

    def post(self, request, *args, **kwargs):
        status = request.POST.get("status")
        request.user.status = status
        request.user.save()
        return JsonResponse({
            "result": True,
            "status": status,
        })


class AwardDetailView(generic.DetailView, MultipleObjectMixin):
    model = u_model.User
    template_name = "users/awards.html"
    context_object_name = "user"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = self.object.awarded_user.all()
        context = super().get_context_data(object_list=object_list, **kwargs)
        return context


class AwardAddView(generic.CreateView):
    model = u_model.UserAward
    user_id = None
    fields = ["award", "message"]
    success_url = "/"

    def get_context_data(self, **kwargs):
        awards = u_model.Award.objects.all()
        context = super().get_context_data(awards=awards)
        return context

    def get(self, request, *args, **kwargs):
        get = util.view_get(request, int(self.kwargs["user_id"]), "users.add_useraward", "add_award")
        if get is True:
            return super().get(self, request, *args, **kwargs)
        return get

    def post(self, request, *args, **kwargs):
        author = request.user
        value = int(request.POST.get('value'))
        message = request.POST.get('msg')
        user = util.get_user_by_id_or_response(int(self.kwargs["user_id"]))
        award = u_model.UserAward(author=author, awarded=user, award_id=value, message=message)
        award.save()
        return JsonResponse({
            "result": "True",
            "awards_num": user.get_awards_count()
        })


class ChangeUsername(generic.FormView):
    form_class = ChangeUsernameForm
    template_name = "users/username_form.html"

    def get_context_data(self, **kwargs):
        price = U_SETTIGNS.nik_price
        context = super().get_context_data(price=price, **kwargs)
        return context

    def post(self, request, *args, **kwargs):
        new_username = request.POST.get("new_username")
        if not bool(re.match(r'^[\w.@+-]+\Z', new_username)):
            return JsonResponse({
                "result": False,
                "cause": "Имя пользователя не валидно, т.к. содержит запрещенные символы",
            })
        if u_model.User.objects.filter(username=new_username):
            return JsonResponse({
                "result": False,
                "cause": "Имя пользователя уже занято. Придумайте другое",
            })
        request.user.username = new_username

users/views/edit.py
import sys
from io import BytesIO

from PIL import Image, ImageSequence
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.http.response import JsonResponse
from django.views.generic import UpdateView

from users.forms import PhotoForm
from users.models import User
from utils.views.mixins import JsonableResponseMixin


class CurrentUserMixin(object):
    model = User

    def get_object(self, *args, **kwargs):
        try:
            obj = super(CurrentUserMixin, self).get_object(*args, **kwargs)
        except AttributeError:
            # SingleObjectMixin throws an AttributeError when no pk or slug
            # is present on the url. In those cases, we use the current user
            obj = self.request.user

        return obj


class UserEdit(CurrentUserMixin, JsonableResponseMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "birthday", "gender", "country", "state", "signature"]
    template_name = "users/edit/user_form.html"
    success_url = "/"

    def post(self, request, *args, **kwargs):
        user = request.user
        form = self.get_form()
        print(request.POST.get("signature"), request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            for key, value in form.cleaned_data.items():
                if getattr(user, key) != value:
                    print(key, value)
                    setattr(user, key, value)
                # if key == "signature":
                #
                #     signature = bleach.clean(request.POST.get("signature"))
                #     setattr(user, key, signature)
                #     print(signature)
            user.save()
            return JsonResponse({"result": True})
        return self.form_invalid(form=form, request=request)


class AvatarChanging(CurrentUserMixin, UpdateView):
    form_class = PhotoForm
    template_name = "users/edit/avatar_form.html"

    def get_context_data(self, **kwargs):
        referer = self.request.META.get('HTTP_REFERER')
        context = super().get_context_data(referer=referer, **kwargs)
        return context

    def post(self, request, *args, **kwargs):
        user = request.user
        form = self.get_form()
        print(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            w = form.cleaned_data.get('width')
            h = form.cleaned_data.get('height')
            name = form.cleaned_data.get('avatar').name

            image = Image.open(form.cleaned_data.get('avatar'))
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((165, 215), Image.ANTIALIAS)
            tempfile_io = BytesIO()
            if image.format in ["GIF", "WEBP"]:
                img_seq = []
                for frame in ImageSequence.Iterator(image):
                    frame.convert('RGBA')
                    frame.crop((x, y, w + x, h + y))
                    n_frame = frame.resize((165, 215), Image.ANTIALIAS)
                    img_seq.append(n_frame.copy())
                if len(img_seq) > 1:
                    resized_image = img_seq[0]
                    resized_image.save(tempfile_io, format=image.format, save_all=True, append_images=img_seq[1:],
                                       loop=0, duration=len(img_seq) / image.info['duration'] * 150, disposal=2,
                                       palette=True)
                else:
                    resized_image.save(tempfile_io, format=image.format)
            else:
                resized_image.save(tempfile_io, format=image.format)
            resized_image.save(tempfile_io, format=image.format)
            image_file = InMemoryUploadedFile(tempfile_io, None, name, image.get_format_mimetype(),
                                              sys.getsizeof(tempfile_io), None)
            user.avatar.save(name, image_file)
            user.save()
            return JsonResponse({"result": "good", "avatar": user.avatar.url})
        print(form.errors)
        return JsonResponse({"result": "bad"})

templates/users/awards.html
<style>
    .award_item {
        position: relative;
        width: 100%;
        display: flex;
        justify-content: center;
        align-content: center;
        align-items: center;
        border: #9dd02b 3px solid;
        margin: 5px 0;
        border-radius: 5px;
    }

    .aw_img {
        position: relative;
        width: 15%;
        display: flex;
        flex-shrink: unset;
        align-content: center;
        justify-content: center;
    }

    .aw_img img {
        max-height: 200px;
    }

    .aw_descr {
        position: relative;
        display: block;
        width: 85%;
    }

    .aw_descr h4 {
        line-height: 0;
        margin: 1em 0;
    }
</style>
<section id="user_awards" data-current="{{ page_obj.number }}" data-total="{{ page_obj.paginator.num_pages }}">
    <span>Награды пользователя <i>{{ user }}</i>: <strong>{{ user.get_awards_count }}</strong></span>
    <hr>
    <div id="user_awards_page">
        {% for award in object_list %}
            <div class="award_item">
                <div class="aw_img">
                    <img src="{{ award.award.icon.url }}" alt="">
                </div>
                <div class="aw_descr">
                    <h4>{{ award.award.name }}</h4>
                    <p>
                <span>
                    <a class="banHUser" href="{% url "userena_profile_detail" award.author %}" target="_blank">
                        <b>{{ award.author }}</b>
                    </a></span>
                        <span style="float:right;">{{ award.create_datetime }}</span>
                    </p>
                    <hr>
                    <p>{{ award.award.description }}</p>
                    {% if award.message != award.award.name %}
                        <p><i>{{ award.message }}</i></p>
                    {% endif %}

                </div>
            </div>


        {% endfor %}
    </div>
    <div class="pagination">
        <ul>
            {% if page_obj.has_previous %}
                <a href="{% url "users:user_awards" user.id %}?page=1">
                    <li>&laquo;</li>
                </a>
                <a href="{% url "users:user_awards" user.id %}?page={{ page_obj.previous_page_number }}">
                    <li>{{ page_obj.previous_page_number }}</li>
                </a>
            {% endif %}
            <a class="is-active" href="{% url "users:user_awards" user.id %}?page={{ page_obj.number }}">
                <li>{{ page_obj.number }}</li>
            </a>
            {% if page_obj.has_next %}
                <a href="{% url "users:user_awards" user.id %}?page={{ page_obj.next_page_number }}">
                    <li>{{ page_obj.next_page_number }}</li>
                </a>
                <a href="{% url "users:user_awards" user.id %}?page={{ page_obj.paginator.num_pages }}">
                    <li>&raquo;</li>
                </a>
            {% endif %}
        </ul>
    </div>
    </sections>

templates/users/change_status.html
<section id="status_change">
    <p style="text-align: center;color: red;" id="status_cause"></p><br>
    <form method="post" id="status_change_form">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <fieldset>
                <legend>{{ field.label }}</legend>
                {{ field }}
            </fieldset>
        {% endfor %}
        <fieldset>
            <input type="submit" value="Отправить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
</section>

templates/users/img_select.html
{% load static %}
<section id="img_color_select">
    <style>
        .label_full_w {
            width: 100%;
            display: block;
        }
    </style>
    <h3>В данном меню можно сменить иконку и цвет никнейма в чате</h3>
    <p>Ваш баланс: <strong><span id="wnd_my_currency_transfer" data-money="{{ user.money }}">{{ user.money }} ДФ</span></strong>
    </p>
    <p style="text-align: center;color: red;" id="img_color_cause"></p><br>
    <form method="post" id="img_color_select_form">
        {% csrf_token %}
        <fieldset>
            <legend>Иконки:</legend>
            <label class="label_full_w">
            <span style="float: right">
                <i>Цена</i>
                <strong>{{ settings.ico_price }} ДФ</strong>
            </span>
            </label><br>
            {% for choice in form.ico %}
                <span class="radio">{{ choice.tag }}</span>
                <img src="{{ choice.choice_label }}" alt="">
            {% endfor %}
        </fieldset>
        <fieldset>
            <legend>Цвета никнейма:</legend>
            <label class="label_full_w">
            <span style="float: right"><i>Цена</i>
                <strong>{{ settings.color_price }}  ДФ</strong>
            </span>
            </label><br>
            {% for choice in form.color %}
                <span class="radio">{{ choice.tag }}</span>
                <span style="color: {{ choice.choice_label }}"><strong>{{ user.username }}</strong></span>
            {% endfor %}
        </fieldset>
        <fieldset>
            <input type="button"
                   onclick="$('input[name=\'ico\']').prop('checked', false);
                $('input[name=\'color\']').prop('checked', false);"
                   value="Сбросить все"/> |
            <input type="submit" value="Отправить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
</section>

templates/users/money_balance.html
<section id="user_transactions" data-current="{{ page_obj.number }}" data-total="{{ page_obj.paginator.num_pages }}">
    <span>Баланс пользователя <i>{{ user }}</i>:
        <strong><span id="wnd_user_currency">{{ user.money }}</span></strong></span><br>
    <span>Ваш баланс: <strong><span id="wnd_my_currency">{{ user_money }}</span></strong></span><br>
    <hr>
    <div id="user_transactions_page">
        {% for money in object_list %}
            <div class="u-rep-history-item">
                <div class="flex-justify-between">
                    {% if money.from_user %}
                        <span class="u-rep-author"><a class="banHUser"
                                                      href="{% url "userena_profile_detail" money.from_user %}"
                                                      target="_blank">
                <b>{{ money.from_user }}</b>
            </a></span>
                    {% endif %}

                    <span class="transact_value {{ money.get_range.class }}">{{ money.get_range.sign }}{{ money.value }} ДФ</span>
                    <span class="u-rep-date">{{ money.add_datetime }}</span>
                </div>
                <div class="u-rep-subj">{{ money.message | safe }}</div>
                <hr>
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <ul>
            {% if page_obj.has_previous %}
                <a href="{% url "users:user_money" user.id %}?page=1">
                    <li>&laquo;</li>
                </a>
                <a href="{% url "users:user_money" user.id %}?page={{ page_obj.previous_page_number }}">
                    <li>{{ page_obj.previous_page_number }}</li>
                </a>
            {% endif %}
                <a class="is-active" href="#">
                    <li>{{ page_obj.number }}</li>
                </a>
            {% if page_obj.has_next %}
                <a href="{% url "users:user_money" user.id %}?page={{ page_obj.next_page_number }}">
                    <li>{{ page_obj.next_page_number }}</li>
                </a>
                <a href="{% url "users:user_money" user.id %}?page={{ page_obj.paginator.num_pages }}">
                    <li>&raquo;</li>
                </a>
            {% endif %}
        </ul>
    </div>
</section>

templates/users/moneytransaction_form.html
<section id="money_transfer">
    <p style="color: red; text-align: center" id="transfer_fall"></p>
    <span>Ваш баланс: <strong><span id="wnd_my_currency_transfer" data-money="{{ user_money }}">{{ user_money }}</span></strong></span><br>
    <form method="post" id="money_transfer_form">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <fieldset>
                <legend>{{ field.label }}</legend>
                {{ field }}
            </fieldset>
        {% endfor %}
        <fieldset>
            <input type="submit" value="Отправить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
</section>

templates/users/reputation.html
<section id="user_reputation" data-current="{{ page_obj.number }}" data-total="{{ page_obj.paginator.num_pages }}">
    <span>Репутация <i>{{ user }}</i>: <strong>{{ user.respect }}</strong></span>
    <hr>
    <div id="user_reputation_page">
        {% for rep in object_list %}
            <div class="u-rep-history-item">
                <div class="flex-justify-between">
                    <div title="{{ rep.get_level.text }} [{{ rep.get_level.sign }}{{ rep.value }}]"
                         style="width:16px;height:17px;float:left;background: url('/static/post_stalker/ico/{{ rep.get_level.ico }}') no-repeat 0 0; background-size: contain;">
                    </div>
                    <span class="u-rep-author"><a class="banHUser"
                                                  href="{% url "userena_profile_detail" rep.from_user %}"
                                                  target="_blank">
                <b>{{ rep.from_user }}</b>
            </a></span>
                    <span class="u-rep-date">{{ rep.add_datetime }}</span>
                </div>
                <div class="u-rep-subj">{{ rep.subject }}</div>
                <div>
                    {% if rep.message %}
                        <span><b>Ответ</b>: </span>
                        <i><span><i>{{ rep.message }}</i></span></i>
                    {% endif %}
                </div>
                <hr>
            </div>
        {% endfor %}
    </div>
    <div class="pagination p12">
        <ul>
            {% if page_obj.has_previous %}
                <a href="{% url "users:user_reputation" user.id %}?page=1">
                    <li>&laquo;</li>
                </a>
                <a href="{% url "users:user_reputation" user.id %}?page={{ page_obj.previous_page_number }}">
                    <li>{{ page_obj.previous_page_number }}</li>
                </a>
            {% endif %}
            <a class="is-active" href="{% url "users:user_reputation" user.id %}?page={{ page_obj.number }}">
                <li>{{ page_obj.number }}</li>
            </a>
            {% if page_obj.has_next %}
                <a href="{% url "users:user_reputation" user.id %}?page={{ page_obj.next_page_number }}">
                    <li>{{ page_obj.next_page_number }}</li>
                </a>
                <a href="{% url "users:user_reputation" user.id %}?page={{ page_obj.paginator.num_pages }}">
                    <li>&raquo;</li>
                </a>
            {% endif %}
        </ul>
    </div>

</section>

templates/users/reputation_form.html
<section id="respect_changing">
    <form method="post" id="respect_change_form">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <fieldset>
                <legend>{{ field.label }}</legend>
                {{ field }}
            </fieldset>
        {% endfor %}
        <fieldset>
            <input type="submit" value="Отправить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
</section>

templates/users/useraward_form.html
<section id="add_award">
    <style>
        .award_itm_img {
            width: 55px;
            height: 55px;
            background-size: contain;
            float: left;
            margin: 7px;
        }

        #add_award_form {
            float: none;
        }
    </style>
    <p style="color: red; text-align: center" id="award_add_fall"></p>
    <div id="award_view"></div>
    <form method="post" id="add_award_form">
        {% csrf_token %}
        <fieldset>
            <legend>{{ form.award.label }}</legend>
            <label for="{{ form.award.name }}">
                <select name="{{ form.award.name }}" id="{{ form.award.id_for_label }}" required>
                    {% for choice in form.award.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </label>
        </fieldset>
        <fieldset>
            <legend>{{ form.message.label }}</legend>
            <label for="{{ form.message.name }}">
                {{ form.message }}
            </label>
        </fieldset>
        <fieldset>
            <input type="submit" value="Добавить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
    <div id="awards_list" style="display: none">

        {% for award in awards %}
            <div id="award{{ award.id }}" style="width: 100%; float: none;">
                <div class="award_itm_img" style="background-image: url('{{ award.icon.url }}'); display: none;"></div>
                <h5>{{ award.name }}</h5>
                <p>{{ award.description }}</p>
            </div>
        {% endfor %}


    </div>
</section>

templates/users/username_form.html
<section id="change_username">
    <p style="color: red; text-align: center" id="change_username_fall"></p>
    <span>Цена <strong>{{ price }}</strong>
        Ваш баланс: <strong><span>{{ user.money }}</span></strong></span><br>

    <form method="post" id="change_username_form">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <fieldset>
                <legend>{{ field.label }}</legend>
                {{ field }}
            </fieldset>
        {% endfor %}
        <fieldset>
            <input type="submit" value="Изменить">
            <div style="display: inline-block;" class="post_result"></div>
        </fieldset>
    </form>
</section>